name: Build & deploy given Mage-OS repo

on:
  workflow_call:
    inputs:
      repo:
        description: 'The composer repository url'
        required: true
        default: 'https://preview-mirror.mage-os.org/'
        type: string
      entrypoint:
        description: 'The Javascript command to use'
        required: true
        default: 'src/make/mirror.js'
        type: string
      remote_dir:
        description: 'Remote folder where the packages are stored'
        required: true
        default: '/var/www/preview-mirror.mage-os.org/html/'
        type: string
      delete:
        description: 'Remove remote files that do not exist in the build'
        required: false
        default: true
        type: boolean
    secrets:
      SERVER_SSH_KEY:
        description: "SSH Key used to upload to the satis server."
        required: true
      REMOTE_USER:
        description: "The system user used to upload to the satis server."
        required: true

env:
  remote_host: "repo.mage-os.org"
  remote_dir: ${{ inputs.remote_dir || '/var/www/preview-mirror.mage-os.org/html/' }}
  repo: ${{ inputs.repo || 'https://preview-mirror.mage-os.org/' }}
  entrypoint: ${{ inputs.entrypoint || 'src/make/mirror.js' }}
  delete_arg: ${{ inputs.delete && '--delete' || '' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to ${{ inputs.repo || 'https://preview-mirror.mage-os.org/' }}"
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:2.2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: curl -L https://github.com/mage-os/php-dependency-list/raw/main/php-classes.phar -o /usr/local/bin/php-classes.phar && chmod +x /usr/local/bin/php-classes.phar
        name: "Install PHP source code dependency analyzer and make executable (used by nightly build script for base package)"
      
      # Composer create-project and composer require have limited support for commit hashes, they check composer-plugin-api constraints
      # of the specified branch HEAD instead of the specified commit hash. 
      #- run: composer create-project "composer/satis:dev-main#fafc1c2eca6394235f12f8a3ee4da7fc7c9fc874"
      # To work around the limitation, we use: git clone && git install.
      #
      # The fafc1c2eca6394235f12f8a3ee4da7fc7c9fc874 hash is the last satis commit that supports composer 2.2.x, which is currently required by the
      # Magento core dependency laminas/laminas-dependency-plugin
      - run: git clone https://github.com/composer/satis.git satis && cd satis && git checkout fafc1c2eca6394235f12f8a3ee4da7fc7c9fc874 && composer install && cd -
        name: "Install satis"

      - run: npm ci
      - run: node ${{ env.entrypoint }} --outputDir=build/packages --gitRepoDir=generate-repo/repositories --repoUrl="${{ env.repo }}"
        name: "Generate the packages for the composer repo"
      - run: node bin/set-satis-homepage-url.js --satisConfig=satis.json --repoUrl="${{ env.repo }}" > /tmp/satis.json
        name: "Configure satis repository URL so composer knows where to download packages from"
      - run: cat <<< $(jq '."output-dir" = "../build" | .repositories[0].url = "../build/packages"' /tmp/satis.json) > /tmp/satis.json
        name: "Tell satis where to find the generated packages"
      - run: cd satis && bin/satis build /tmp/satis.json ../build && cd -
      - run: cd satis && node ../bin/set-satis-output-url-prefix.js --satisOutputDir=../build --repoUrl="${{ env.repo }}" && cd -
        name: "Fix path to packages in the packages.json satis created"

      - uses: easingthemes/ssh-deploy@v4
        name: "Rsync over SSH"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ env.remote_host }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ env.remote_dir }}
          ARGS: "--verbose --compress --recursive --links --times --omit-dir-times ${{ env.delete_arg }}"
          SOURCE: "build/*"
